name: vct
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7.7
  - pip=20.1.1
  - cudatoolkit=10.2.89
  - pytorch=1.8.1
  - torchvision=0.9.1
  - numpy=1.19.1
  - scipy=1.5.2
  - pip:
    - gin-config==0.4.0
    - timm==0.6.7
    - imageio==2.9.0
    - einops==0.4.1
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - scikit-learn==0.23.2
    - scikit-image==0.17.2
    - tqdm==4.48.2
    - pytorch-lightning==1.5.9
    - absl-py==0.11.0
    - h5py==2.10.0
    - pytorch-pretrained-biggan==0.1.1